services:
  pipeline:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend/gcp-credentials.json:/app/gcp-credentials.json:ro
      - ./pipeline/database.sql:/pipeline/database.sql:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    command: python execution.py

  api:
    build: ./backend
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/gcp-credentials.json:/app/gcp-credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    command: uvicorn api:app --host 0.0.0.0 --port 8080

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://laughing-space-sniffle-wjx466vrj56cw5g-8080.app.github.dev
    environment:
      - NEXT_PUBLIC_API_URL=https://laughing-space-sniffle-wjx466vrj56cw5g-8080.app.github.dev
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app